services:
  # database
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendence_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Backend NestJS
  backend:
    image: backend:1
    build: ./backend
    container_name: nest_backend
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/transcendence_db"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - db
  frontend:
    image: frontend:1
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Important : pour ne pas écraser les modules node du container
    environment:
      - CHOKIDAR_USEPOLLING=true # Pour que le rafraîchissement auto fonctionne sous Docker
      - VITE_PORT=5173
    tty: true
    stdin_open: true
volumes:
  pgdata:
