
services:
  db:
    image: postgres:15-alpine
    container_name: transcendence_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transcendence
    ports:
      -  "5432:5432"
    volumes:
      -  db_data:/var/lib/postgresql/data

volumes:
  db_data:
